services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      
mern-network

  backend:
    build: ./Backend
    container_name: backend
    ports:
      
"5000:5000"
  environment:
MONGO_URI=mongodb://host.docker.internal:27017/MiniCRM

    depends_on:
      
mongodb
  networks:
mern-network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      
"5173:5173"
  depends_on:
backend
networks:
mern-network

networks:
  mern-network:
    driver: bridge